name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # Если ваша основная ветка называется master, замените main на master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка проекта (Build)
        run: npm run build

      - name: Загрузка артефактов
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist' # Для Create React App (CRA) замените 'dist' на 'build'

      - name: Деплой на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
